# create this file under smartcontract-lottery

dependencies:
  -smartcontractkit/chainlink-brownie-contracts@1.1.1
  -OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      -'@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      -'@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  default: development
  keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'//copied from https://docs.chain.link/docs/vrf-contracts/
  fee: 100000000000000000
  
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'//copied from https://docs.chain.link/docs/vrf-contracts/
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'//copied from https://docs.chain.link/docs/ethereum-addresses/
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'copied from https://docs.chain.link/docs/link-token-contracts/
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'//copied from https://docs.chain.link/docs/vrf-contracts/
    fee: 100000000000000000
  mainnet-fork:
    eth_usd_price_feed:'0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'//copied from https://docs.chain.link/docs/ethereum-addresses/
wallets:
  from_key:${PRIVATE_KEY}  
