# create this file under smartcontract-lottery

dependencies:
  -smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    reamppings:
      -'@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
